### ISSUE TITLE
Platform not found: 'text_sensor.ntp_server_info'.

### ISSUE THREAD

**Issue by innx2020** [RobertJN64/ESPHome-NTP-Server#10]
Thank you for creating the ntp-server component. 

`text_sensor:
  - platform: ntp_server_info
    time:
      name: NTP Server Info
`

esphome 2025.5.0

error Platform not found: 'text_sensor.ntp_server_info'.

**Comment by RobertJN64** [comment]
Make sure you include these components as they are not part of the core esphome library:

```
external_components:
  source:
    type: git
    url: https://github.com/RobertJN64/ESPHome-NTP-Server
```

If this doesn't work can you send your full yaml file?
